name: "deploy to netlify"

on: 
  push:
    branches:
      - main
      - feature-*
      - bugfix-*
  pull_request:
    branches:
      - main
      - feature-*
      - bugfix-*
    paths:
      - package.json
      - CHANGELOG

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci


# deploy the application to netlify
      - name: Deploying to Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: ${{ secrets.CORE_GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './build'
          comment-on-commit: true
